### ISSUE TITLE
create the difference function

### ISSUE THREAD

**Issue by aliccee** [dsi-principles-prog/midterm-aliccee#1]
find the difference in health scores between 2016 and 2017.
 The output is numeric.

Asset function:
assert(within_bounds(lower.bound = -Inf, upper.bound = Inf, allow.na = FALSE), Health_Difference)

**Comment by ArsalanRiaz** [comment]
Function Name: Health_Difference
Column Name: Health_Difference

The Health Difference functions subtracts the health life expectancy of 2017 from health life expectancy of 2016. This column generated will show the Heath Difference which can have a positive as well as a negative trend.
