### ISSUE TITLE
create get_social_satis funciton

### ISSUE THREAD

**Issue by aliccee** [dsi-principles-prog/midterm-aliccee#2]
create a function to get the social satisfaction score.

You should combine these parameters towards social satisfaction, which including economy_gdp_per_capita.x, trust_government_corruption.x, dystopia_residual.x.

The output should be numeric.

Asset function as following:
  assert(within_bounds(lower.bound = 0, upper.bound = Inf, allow.na = FALSE), social_satis)

**Comment by ArsalanRiaz** [comment]
Function Name: get_social_satis
Column Name: social_satis

Gives the social satisfaction score by taking a sum of economy_gdp_per_capita.x, trust_government_corruption.x and dystopia_residual.x which will 'be a key factor in determining the happiness rank and happiness score. It individually can be used as a feature
